### ISSUE TITLE
Plz fix readme

### ISSUE THREAD

**Issue by yonghun8343** [PhilJay/APNJWT#1]
when i make token decoder and i know it's typo at readme

    private val jsonDecoder = object : JsonDecoder<JWTAuthHeader, JWTAuthPayload> {

        override fun headerFrom(json: String): JWTAuthHeader {
            return gson.fromJson(json, JWTAuthHeader::class.java)
        }

        override fun palyoadFrom(json: String): JWTAuthPayload { << **palyoadFrom to payloadFrom**
            return gson.fromJson(json, JWTAuthPayload::class.java)
        }
    }

**Comment by PhilJay** [comment]
Ty
