### ISSUE TITLE
Could not find com.github.PhilJay:JWT:1.1.5

### ISSUE THREAD

**Issue by semnazri** [PhilJay/APNJWT#2]
Hi there,
i'm trying to use this library in android studio, but i get some error in gradle file, like 
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.PhilJay:JWT:1.1.5.
Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/PhilJay/JWT/1.1.5/JWT-1.1.5.pom
       - https://jcenter.bintray.com/com/github/PhilJay/JWT/1.1.5/JWT-1.1.5.pom

**Comment by PhilJay** [comment]
You need to add the Jitpack repository to your build.gradle:

```
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```
